### PR TITLE
Sword/Shield updates

### LINKED ISSUE #23: [SH] Randomize Learn: 'Index was outside the bounds of the array.'
Comes up when pressing the Randomize button under the Randomize Learn tab in the Pokémon Editor. This is on a clean rip of the game files. Everything is completely untouched.

Full details:
https://pastebin.com/GagCZM60

Linking to pastebin because posting something that tall makes me feel like I'm spamming.

### LINKED ISSUE #33: No more option for a Pokemon's ability in trainer editor
Hey just wanted to notify you guys that after the changes today to the trainer editor to allow editing of the Dynamax levels and other features, the box to decide a Pokemon's ability is no loner there. Also, there's a "Can mega" checkbox now. Not sure if this was intentional or not.

Anyways, there is currently no way to change trainer Pokemon abilities with the latest commits.

### PR DESCRIPTION
**Pull request by sora10pls**
Related: #40

Changes proposed in this PR include:

* Add Species banlist when randomizing Trainer PKM in SWSH
  * Resolves #23 and #38
* Add Galarian Forms to Form Randomization
  * Handling for Meowth/Darmanitan (Altform 2 vs Altform 1)
  * Always `false` with LGPE
* Add Held Item Randomization when randomizing Trainer PKM
* Add the remaining Kanto 68x56 sprites from LGPE
* Add Level Boost option to Wild Editors
* Add more discovered Crash Classes
* Add Melony to SWSH Important Trainers
* Update `Tables8` with data from PKHeX
* Update several editors to fit 68x56 sprites
* Fix FlowLayoutPanels for Ability/Held Item being hidden on `TrainerPoke8`
  * Resolves #33 
* Hide Dynamax Level/CanGigantamax on `TrainerPoke7b`
* Hide Hidden Power Type on `TrainerPoke8`
* Always disallow Eternamax Eternatus when randomizing

### CODE REVIEW

**Comment by SnakeDeath** [comment]
also adding a way to know overworld pokemon from non-overworld pokemon in the randomization option (if im wrong about this and it already exist please correct me).

**Comment by sora10pls** [comment]
@SnakeDeath The bottom-left of the Wild Editor will read either “Symbols” or “Hidden”.

“Symbols” are symbol encounters, the visible Pokémon you see running around.

“Hidden” are random encounters, the Pokémon hiding in tall grass (the ! markers).

**Comment by SnakeDeath** [comment]
@sora10pls I see thank you ,so Wild_SW it means the wild pokemon in pokemon sword right ? and Wild_SH for pokemon shield (or it depends on the files that we select?) , i feel like im wrong because for example in route 1 in Wild_SW its only "Hidden" and in Wild_SH its only “Symbols” ,so basically Wild_SW its the opposite of Wild_SH almost in all routes

**Comment by sora10pls** [comment]
@SnakeDeath Correct. Both games store the wild encounter data for both versions and the code dynamically picks which data to load.

As for your previous tests, you probably aren’t using the latest commit — it works fine for me showing a symbol table and a hidden table.

**Comment by SnakeDeath** [comment]
@sora10pls ok will try it, thank you

**Comment by SnakeDeath** [comment]
@sora10pls yep it worked ty i was using the files from the master branch

**Comment by huynht12** [comment]
Is there a way to edit the raid max encounters yet? I see that theres an option to dump their data but nowhere to edit them.

**Pull request merged**
